In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [7]:
data = pd.read_csv(r"P:\Data mining\Project\Data\netflix_titles.csv")
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

# Data Cleaning

In [11]:
data = data.dropna()
data = data.reset_index(drop=True)

In [12]:
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
1,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
2,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
3,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis NiewÃ¶hner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
4,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...
...,...,...,...,...,...,...,...,...,...,...,...,...
5327,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
5328,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
5329,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
5330,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
5331,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [13]:
data['cast'] = data['cast'].str.split(',')

In [15]:
df_temp = pd.DataFrame(data['cast'].tolist()).fillna('').add_prefix('cast_')

In [16]:
data = pd.concat([data, df_temp], axis=1)

In [17]:
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,cast_34,cast_35,cast_36,cast_37,cast_38,cast_39,cast_40,cast_41,cast_42,cast_43
0,s8,Movie,Sankofa,Haile Gerima,"[Kofi Ghanaba, Oyafunmike Ogunlano, Alexandr...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,...,,,,,,,,,,
1,s9,TV Show,The Great British Baking Show,Andy Devonshire,"[Mel Giedroyc, Sue Perkins, Mary Berry, Pau...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,...,,,,,,,,,,
2,s10,Movie,The Starling,Theodore Melfi,"[Melissa McCarthy, Chris O'Dowd, Kevin Kline...",United States,"September 24, 2021",2021,PG-13,104 min,...,,,,,,,,,,
3,s13,Movie,Je Suis Karl,Christian Schwochow,"[Luna Wedler, Jannis NiewÃ¶hner, Milan Pesche...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,...,,,,,,,,,,
4,s25,Movie,Jeans,S. Shankar,"[Prashanth, Aishwarya Rai Bachchan, Sri Laks...",India,"September 21, 2021",1998,TV-14,166 min,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5327,s8802,Movie,Zinzana,Majid Al Ansari,"[Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jab...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,...,,,,,,,,,,
5328,s8803,Movie,Zodiac,David Fincher,"[Mark Ruffalo, Jake Gyllenhaal, Robert Downe...",United States,"November 20, 2019",2007,R,158 min,...,,,,,,,,,,
5329,s8805,Movie,Zombieland,Ruben Fleischer,"[Jesse Eisenberg, Woody Harrelson, Emma Ston...",United States,"November 1, 2019",2009,R,88 min,...,,,,,,,,,,
5330,s8806,Movie,Zoom,Peter Hewitt,"[Tim Allen, Courteney Cox, Chevy Chase, Kat...",United States,"January 11, 2020",2006,PG,88 min,...,,,,,,,,,,
5331,s8807,Movie,Zubaan,Mozez Singh,"[Vicky Kaushal, Sarah-Jane Dias, Raaghav Cha...",India,"March 2, 2019",2015,TV-14,111 min,...,,,,,,,,,,

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5332 entries, 0 to 5331
Data columns (total 56 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       5332 non-null   object
 1   type          5332 non-null   object
 2   title         5332 non-null   object
 3   director      5332 non-null   object
 4   cast          5332 non-null   object
 5   country       5332 non-null   object
 6   date_added    5332 non-null   object
 7   release_year  5332 non-null   int64
 8   rating        5332 non-null   object
 9   duration      5332 non-null   object
 10  listed_in     5332 non-null   object
 11  description   5332 non-null   object
 12  cast_0        5332 non-null   object
 13  cast_1        5332 non-null   object
 14  cast_2        5332 non-null   object
 15  cast_3        5332 non-null   object
 16  cast_4        5332 non-null   object
 17  cast_5        5332 non-null   object
 18  cast_6        5332 non-null   object
 19  cast_7        5332 non-null   object
 20  cast_8        5332 non-null   object
 21  cast_9        5332 non-null   object
 22  cast_10       5332 non-null   object
 23  cast_11       5332 non-null   object
 24  cast_12       5332 non-null   object
 25  cast_13       5332 non-null   object
 26  cast_14       5332 non-null   object
 27  cast_15       5332 non-null   object
 28  cast_16       5332 non-null   object
 29  cast_17       5332 non-null   object
 30  cast_18       5332 non-null   object
 31  cast_19       5332 non-null   object
 32  cast_20       5332 non-null   object
 33  cast_21       5332 non-null   object
 34  cast_22       5332 non-null   object
 35  cast_23       5332 non-null   object
 36  cast_24       5332 non-null   object
 37  cast_25       5332 non-null   object
 38  cast_26       5332 non-null   object
 39  cast_27       5332 non-null   object
 40  cast_28       5332 non-null   object
 41  cast_29       5332 non-null   object
 42  cast_30       5332 non-null   object
 43  cast_31       5332 non-null   object
 44  cast_32       5332 non-null   object
 45  cast_33       5332 non-null   object
 46  cast_34       5332 non-null   object
 47  cast_35       5332 non-null   object
 48  cast_36       5332 non-null   object
 49  cast_37       5332 non-null   object
 50  cast_38       5332 non-null   object
 51  cast_39       5332 non-null   object
 52  cast_40       5332 non-null   object
 53  cast_41       5332 non-null   object
 54  cast_42       5332 non-null   object
 55  cast_43       5332 non-null   object
dtypes: int64(1), object(55)
memory usage: 2.3+ MB

In [27]:
data['cast_6']

0          Reggie Carter
1
2          Laura Harrier
3         Victor Boccard
4
              ...
5327
5328         Donal Logue
5329          Derek Graf
5330     Spencer Breslin
5331      Anita Shabdish
Name: cast_6, Length: 5332, dtype: object

In [23]:
data = data.dropna()
data = data.reset_index(drop=True)

In [24]:
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,cast_34,cast_35,cast_36,cast_37,cast_38,cast_39,cast_40,cast_41,cast_42,cast_43
0,s8,Movie,Sankofa,Haile Gerima,"[Kofi Ghanaba, Oyafunmike Ogunlano, Alexandr...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,...,,,,,,,,,,
1,s9,TV Show,The Great British Baking Show,Andy Devonshire,"[Mel Giedroyc, Sue Perkins, Mary Berry, Pau...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,...,,,,,,,,,,
2,s10,Movie,The Starling,Theodore Melfi,"[Melissa McCarthy, Chris O'Dowd, Kevin Kline...",United States,"September 24, 2021",2021,PG-13,104 min,...,,,,,,,,,,
3,s13,Movie,Je Suis Karl,Christian Schwochow,"[Luna Wedler, Jannis NiewÃ¶hner, Milan Pesche...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,...,,,,,,,,,,
4,s25,Movie,Jeans,S. Shankar,"[Prashanth, Aishwarya Rai Bachchan, Sri Laks...",India,"September 21, 2021",1998,TV-14,166 min,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5327,s8802,Movie,Zinzana,Majid Al Ansari,"[Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jab...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,...,,,,,,,,,,
5328,s8803,Movie,Zodiac,David Fincher,"[Mark Ruffalo, Jake Gyllenhaal, Robert Downe...",United States,"November 20, 2019",2007,R,158 min,...,,,,,,,,,,
5329,s8805,Movie,Zombieland,Ruben Fleischer,"[Jesse Eisenberg, Woody Harrelson, Emma Ston...",United States,"November 1, 2019",2009,R,88 min,...,,,,,,,,,,
5330,s8806,Movie,Zoom,Peter Hewitt,"[Tim Allen, Courteney Cox, Chevy Chase, Kat...",United States,"January 11, 2020",2006,PG,88 min,...,,,,,,,,,,
5331,s8807,Movie,Zubaan,Mozez Singh,"[Vicky Kaushal, Sarah-Jane Dias, Raaghav Cha...",India,"March 2, 2019",2015,TV-14,111 min,...,,,,,,,,,,

In [29]:
data.drop(data.iloc[:,21:],inplace=True, axis=1)

In [30]:
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,description,cast_0,cast_1,cast_2,cast_3,cast_4,cast_5,cast_6,cast_7,cast_8
0,s8,Movie,Sankofa,Haile Gerima,"[Kofi Ghanaba, Oyafunmike Ogunlano, Alexandr...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,...,"On a photo shoot in Ghana, an American model s...",Kofi Ghanaba,Oyafunmike Ogunlano,Alexandra Duah,Nick Medley,Mutabaruka,Afemo Omilami,Reggie Carter,Mzuri,
1,s9,TV Show,The Great British Baking Show,Andy Devonshire,"[Mel Giedroyc, Sue Perkins, Mary Berry, Pau...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,...,A talented batch of amateur bakers face off in...,Mel Giedroyc,Sue Perkins,Mary Berry,Paul Hollywood,,,,,
2,s10,Movie,The Starling,Theodore Melfi,"[Melissa McCarthy, Chris O'Dowd, Kevin Kline...",United States,"September 24, 2021",2021,PG-13,104 min,...,A woman adjusting to life after a loss contend...,Melissa McCarthy,Chris O'Dowd,Kevin Kline,Timothy Olyphant,Daveed Diggs,Skyler Gisondo,Laura Harrier,Rosalind Chao,Kimberly Quinn
3,s13,Movie,Je Suis Karl,Christian Schwochow,"[Luna Wedler, Jannis NiewÃ¶hner, Milan Pesche...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,...,After most of her family is murdered in a terr...,Luna Wedler,Jannis NiewÃ¶hner,Milan Peschel,Edin HasanoviÄ‡,Anna FialovÃ¡,Marlon Boess,Victor Boccard,Fleur Geffrier,Aziz Dyab
4,s25,Movie,Jeans,S. Shankar,"[Prashanth, Aishwarya Rai Bachchan, Sri Laks...",India,"September 21, 2021",1998,TV-14,166 min,...,When the father of the man she loves insists t...,Prashanth,Aishwarya Rai Bachchan,Sri Lakshmi,Nassar,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5327,s8802,Movie,Zinzana,Majid Al Ansari,"[Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jab...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,...,Recovering alcoholic Talal wakes up inside a s...,Ali Suliman,Saleh Bakri,Yasa,Ali Al-Jabri,Mansoor Alfeeli,Ahd,,,
5328,s8803,Movie,Zodiac,David Fincher,"[Mark Ruffalo, Jake Gyllenhaal, Robert Downe...",United States,"November 20, 2019",2007,R,158 min,...,"A political cartoonist, a crime reporter and a...",Mark Ruffalo,Jake Gyllenhaal,Robert Downey Jr.,Anthony Edwards,Brian Cox,Elias Koteas,Donal Logue,John Carroll Lynch,Dermot Mulroney
5329,s8805,Movie,Zombieland,Ruben Fleischer,"[Jesse Eisenberg, Woody Harrelson, Emma Ston...",United States,"November 1, 2019",2009,R,88 min,...,Looking to survive in a world taken over by zo...,Jesse Eisenberg,Woody Harrelson,Emma Stone,Abigail Breslin,Amber Heard,Bill Murray,Derek Graf,,
5330,s8806,Movie,Zoom,Peter Hewitt,"[Tim Allen, Courteney Cox, Chevy Chase, Kat...",United States,"January 11, 2020",2006,PG,88 min,...,"Dragged from civilian life, a former superhero...",Tim Allen,Courteney Cox,Chevy Chase,Kate Mara,Ryan Newman,Michael Cassidy,Spencer Breslin,Rip Torn,Kevin Zegers
5331,s8807,Movie,Zubaan,Mozez Singh,"[Vicky Kaushal, Sarah-Jane Dias, Raaghav Cha...",India,"March 2, 2019",2015,TV-14,111 min,...,A scrappy but poor boy worms his way into a ty...,Vicky Kaushal,Sarah-Jane Dias,Raaghav Chanana,Manish Chaudhary,Meghna Malik,Malkeet Rauni,Anita Shabdish,Chittaranjan Tripathy,

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5332 entries, 0 to 5331
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       5332 non-null   object
 1   type          5332 non-null   object
 2   title         5332 non-null   object
 3   director      5332 non-null   object
 4   cast          5332 non-null   object
 5   country       5332 non-null   object
 6   date_added    5332 non-null   object
 7   release_year  5332 non-null   int64
 8   rating        5332 non-null   object
 9   duration      5332 non-null   object
 10  listed_in     5332 non-null   object
 11  description   5332 non-null   object
 12  cast_0        5332 non-null   object
 13  cast_1        5332 non-null   object
 14  cast_2        5332 non-null   object
 15  cast_3        5332 non-null   object
 16  cast_4        5332 non-null   object
 17  cast_5        5332 non-null   object
 18  cast_6        5332 non-null   object
 19  cast_7        5332 non-null   object
 20  cast_8        5332 non-null   object
dtypes: int64(1), object(20)
memory usage: 874.9+ KB

In [33]:
data['listed_in'] = data['listed_in'].str.split(',')

In [34]:
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,description,cast_0,cast_1,cast_2,cast_3,cast_4,cast_5,cast_6,cast_7,cast_8
0,s8,Movie,Sankofa,Haile Gerima,"[Kofi Ghanaba, Oyafunmike Ogunlano, Alexandr...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,...,"On a photo shoot in Ghana, an American model s...",Kofi Ghanaba,Oyafunmike Ogunlano,Alexandra Duah,Nick Medley,Mutabaruka,Afemo Omilami,Reggie Carter,Mzuri,
1,s9,TV Show,The Great British Baking Show,Andy Devonshire,"[Mel Giedroyc, Sue Perkins, Mary Berry, Pau...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,...,A talented batch of amateur bakers face off in...,Mel Giedroyc,Sue Perkins,Mary Berry,Paul Hollywood,,,,,
2,s10,Movie,The Starling,Theodore Melfi,"[Melissa McCarthy, Chris O'Dowd, Kevin Kline...",United States,"September 24, 2021",2021,PG-13,104 min,...,A woman adjusting to life after a loss contend...,Melissa McCarthy,Chris O'Dowd,Kevin Kline,Timothy Olyphant,Daveed Diggs,Skyler Gisondo,Laura Harrier,Rosalind Chao,Kimberly Quinn
3,s13,Movie,Je Suis Karl,Christian Schwochow,"[Luna Wedler, Jannis NiewÃ¶hner, Milan Pesche...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,...,After most of her family is murdered in a terr...,Luna Wedler,Jannis NiewÃ¶hner,Milan Peschel,Edin HasanoviÄ‡,Anna FialovÃ¡,Marlon Boess,Victor Boccard,Fleur Geffrier,Aziz Dyab
4,s25,Movie,Jeans,S. Shankar,"[Prashanth, Aishwarya Rai Bachchan, Sri Laks...",India,"September 21, 2021",1998,TV-14,166 min,...,When the father of the man she loves insists t...,Prashanth,Aishwarya Rai Bachchan,Sri Lakshmi,Nassar,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5327,s8802,Movie,Zinzana,Majid Al Ansari,"[Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jab...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,...,Recovering alcoholic Talal wakes up inside a s...,Ali Suliman,Saleh Bakri,Yasa,Ali Al-Jabri,Mansoor Alfeeli,Ahd,,,
5328,s8803,Movie,Zodiac,David Fincher,"[Mark Ruffalo, Jake Gyllenhaal, Robert Downe...",United States,"November 20, 2019",2007,R,158 min,...,"A political cartoonist, a crime reporter and a...",Mark Ruffalo,Jake Gyllenhaal,Robert Downey Jr.,Anthony Edwards,Brian Cox,Elias Koteas,Donal Logue,John Carroll Lynch,Dermot Mulroney
5329,s8805,Movie,Zombieland,Ruben Fleischer,"[Jesse Eisenberg, Woody Harrelson, Emma Ston...",United States,"November 1, 2019",2009,R,88 min,...,Looking to survive in a world taken over by zo...,Jesse Eisenberg,Woody Harrelson,Emma Stone,Abigail Breslin,Amber Heard,Bill Murray,Derek Graf,,
5330,s8806,Movie,Zoom,Peter Hewitt,"[Tim Allen, Courteney Cox, Chevy Chase, Kat...",United States,"January 11, 2020",2006,PG,88 min,...,"Dragged from civilian life, a former superhero...",Tim Allen,Courteney Cox,Chevy Chase,Kate Mara,Ryan Newman,Michael Cassidy,Spencer Breslin,Rip Torn,Kevin Zegers
5331,s8807,Movie,Zubaan,Mozez Singh,"[Vicky Kaushal, Sarah-Jane Dias, Raaghav Cha...",India,"March 2, 2019",2015,TV-14,111 min,...,A scrappy but poor boy worms his way into a ty...,Vicky Kaushal,Sarah-Jane Dias,Raaghav Chanana,Manish Chaudhary,Meghna Malik,Malkeet Rauni,Anita Shabdish,Chittaranjan Tripathy,

In [35]:
df_temp = pd.DataFrame(data['listed_in'].tolist()).add_prefix('genre_')

In [36]:
data = pd.concat([data, df_temp], axis=1)

In [37]:
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,cast_2,cast_3,cast_4,cast_5,cast_6,cast_7,cast_8,genre_0,genre_1,genre_2
0,s8,Movie,Sankofa,Haile Gerima,"[Kofi Ghanaba, Oyafunmike Ogunlano, Alexandr...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,...,Alexandra Duah,Nick Medley,Mutabaruka,Afemo Omilami,Reggie Carter,Mzuri,,Dramas,Independent Movies,International Movies
1,s9,TV Show,The Great British Baking Show,Andy Devonshire,"[Mel Giedroyc, Sue Perkins, Mary Berry, Pau...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,...,Mary Berry,Paul Hollywood,,,,,,British TV Shows,Reality TV,None
2,s10,Movie,The Starling,Theodore Melfi,"[Melissa McCarthy, Chris O'Dowd, Kevin Kline...",United States,"September 24, 2021",2021,PG-13,104 min,...,Kevin Kline,Timothy Olyphant,Daveed Diggs,Skyler Gisondo,Laura Harrier,Rosalind Chao,Kimberly Quinn,Comedies,Dramas,None
3,s13,Movie,Je Suis Karl,Christian Schwochow,"[Luna Wedler, Jannis NiewÃ¶hner, Milan Pesche...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,...,Milan Peschel,Edin HasanoviÄ‡,Anna FialovÃ¡,Marlon Boess,Victor Boccard,Fleur Geffrier,Aziz Dyab,Dramas,International Movies,None
4,s25,Movie,Jeans,S. Shankar,"[Prashanth, Aishwarya Rai Bachchan, Sri Laks...",India,"September 21, 2021",1998,TV-14,166 min,...,Sri Lakshmi,Nassar,,,,,,Comedies,International Movies,Romantic Movies
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5327,s8802,Movie,Zinzana,Majid Al Ansari,"[Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jab...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,...,Yasa,Ali Al-Jabri,Mansoor Alfeeli,Ahd,,,,Dramas,International Movies,Thrillers
5328,s8803,Movie,Zodiac,David Fincher,"[Mark Ruffalo, Jake Gyllenhaal, Robert Downe...",United States,"November 20, 2019",2007,R,158 min,...,Robert Downey Jr.,Anthony Edwards,Brian Cox,Elias Koteas,Donal Logue,John Carroll Lynch,Dermot Mulroney,Cult Movies,Dramas,Thrillers
5329,s8805,Movie,Zombieland,Ruben Fleischer,"[Jesse Eisenberg, Woody Harrelson, Emma Ston...",United States,"November 1, 2019",2009,R,88 min,...,Emma Stone,Abigail Breslin,Amber Heard,Bill Murray,Derek Graf,,,Comedies,Horror Movies,None
5330,s8806,Movie,Zoom,Peter Hewitt,"[Tim Allen, Courteney Cox, Chevy Chase, Kat...",United States,"January 11, 2020",2006,PG,88 min,...,Chevy Chase,Kate Mara,Ryan Newman,Michael Cassidy,Spencer Breslin,Rip Torn,Kevin Zegers,Children & Family Movies,Comedies,None
5331,s8807,Movie,Zubaan,Mozez Singh,"[Vicky Kaushal, Sarah-Jane Dias, Raaghav Cha...",India,"March 2, 2019",2015,TV-14,111 min,...,Raaghav Chanana,Manish Chaudhary,Meghna Malik,Malkeet Rauni,Anita Shabdish,Chittaranjan Tripathy,,Dramas,International Movies,Music & Musicals

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5332 entries, 0 to 5331
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       5332 non-null   object
 1   type          5332 non-null   object
 2   title         5332 non-null   object
 3   director      5332 non-null   object
 4   cast          5332 non-null   object
 5   country       5332 non-null   object
 6   date_added    5332 non-null   object
 7   release_year  5332 non-null   int64
 8   rating        5332 non-null   object
 9   duration      5332 non-null   object
 10  listed_in     5332 non-null   object
 11  description   5332 non-null   object
 12  cast_0        5332 non-null   object
 13  cast_1        5332 non-null   object
 14  cast_2        5332 non-null   object
 15  cast_3        5332 non-null   object
 16  cast_4        5332 non-null   object
 17  cast_5        5332 non-null   object
 18  cast_6        5332 non-null   object
 19  cast_7        5332 non-null   object
 20  cast_8        5332 non-null   object
 21  genre_0       5332 non-null   object
 22  genre_1       4231 non-null   object
 23  genre_2       2295 non-null   object
dtypes: int64(1), object(23)
memory usage: 999.9+ KB

In [39]:
data = data.dropna()
data = data.reset_index(drop=True)

In [40]:
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,cast_2,cast_3,cast_4,cast_5,cast_6,cast_7,cast_8,genre_0,genre_1,genre_2
0,s8,Movie,Sankofa,Haile Gerima,"[Kofi Ghanaba, Oyafunmike Ogunlano, Alexandr...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,...,Alexandra Duah,Nick Medley,Mutabaruka,Afemo Omilami,Reggie Carter,Mzuri,,Dramas,Independent Movies,International Movies
1,s25,Movie,Jeans,S. Shankar,"[Prashanth, Aishwarya Rai Bachchan, Sri Laks...",India,"September 21, 2021",1998,TV-14,166 min,...,Sri Lakshmi,Nassar,,,,,,Comedies,International Movies,Romantic Movies
2,s42,Movie,Jaws,Steven Spielberg,"[Roy Scheider, Robert Shaw, Richard Dreyfuss...",United States,"September 16, 2021",1975,PG,124 min,...,Richard Dreyfuss,Lorraine Gary,Murray Hamilton,Carl Gottlieb,Jeffrey Kramer,Susan Backlinie,Jonathan Filley,Action & Adventure,Classic Movies,Dramas
3,s43,Movie,Jaws 2,Jeannot Szwarc,"[Roy Scheider, Lorraine Gary, Murray Hamilto...",United States,"September 16, 2021",1978,PG,116 min,...,Murray Hamilton,Joseph Mascolo,Jeffrey Kramer,Collin Wilcox Paxton,Ann Dusenberry,Mark Gruner,Barry Coe,Dramas,Horror Movies,Thrillers
4,s44,Movie,Jaws 3,Joe Alves,"[Dennis Quaid, Bess Armstrong, Simon MacCork...",United States,"September 16, 2021",1983,PG,98 min,...,Simon MacCorkindale,Louis Gossett Jr.,John Putch,Lea Thompson,P.H. Moriarty,Dan Blasko,Liz Morris,Action & Adventure,Horror Movies,Thrillers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2290,s8795,Movie,Ø§Ø´ØªØ¨Ø§Ùƒ,Mohamed Diab,"[Nelly Karim, Hany Adel, Tarek Abdel Aziz, ...","Egypt, France","October 11, 2018",2016,TV-14,98 min,...,Tarek Abdel Aziz,Ahmed Malek,Ahmed Dash,Husni Sheta,Aly Eltayeb,Amr El Kady,Mohamed Abd El Azim,Dramas,Independent Movies,International Movies
2291,s8799,Movie,Zed Plus,Chandra Prakash Dwivedi,"[Adil Hussain, Mona Singh, K.K. Raina, Sanj...",India,"December 31, 2019",2014,TV-MA,131 min,...,K.K. Raina,Sanjay Mishra,Anil Rastogi,Ravi Jhankal,Kulbhushan Kharbanda,Ekavali Khanna,Mukesh Tiwari,Comedies,Dramas,International Movies
2292,s8802,Movie,Zinzana,Majid Al Ansari,"[Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jab...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,...,Yasa,Ali Al-Jabri,Mansoor Alfeeli,Ahd,,,,Dramas,International Movies,Thrillers
2293,s8803,Movie,Zodiac,David Fincher,"[Mark Ruffalo, Jake Gyllenhaal, Robert Downe...",United States,"November 20, 2019",2007,R,158 min,...,Robert Downey Jr.,Anthony Edwards,Brian Cox,Elias Koteas,Donal Logue,John Carroll Lynch,Dermot Mulroney,Cult Movies,Dramas,Thrillers
2294,s8807,Movie,Zubaan,Mozez Singh,"[Vicky Kaushal, Sarah-Jane Dias, Raaghav Cha...",India,"March 2, 2019",2015,TV-14,111 min,...,Raaghav Chanana,Manish Chaudhary,Meghna Malik,Malkeet Rauni,Anita Shabdish,Chittaranjan Tripathy,,Dramas,International Movies,Music & Musicals

In [50]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2295 entries, 0 to 2294
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       2295 non-null   object
 1   type          2295 non-null   object
 2   title         2295 non-null   object
 3   director      2295 non-null   object
 4   cast          2295 non-null   object
 5   country       2295 non-null   object
 6   date_added    2295 non-null   object
 7   release_year  2295 non-null   int64
 8   rating        2295 non-null   object
 9   duration      2295 non-null   object
 10  listed_in     2295 non-null   object
 11  description   2295 non-null   object
 12  cast_0        2295 non-null   object
 13  cast_1        2295 non-null   object
 14  cast_2        2295 non-null   object
 15  cast_3        2295 non-null   object
 16  cast_4        2295 non-null   object
 17  cast_5        2295 non-null   object
 18  cast_6        2295 non-null   object
 19  cast_7        2295 non-null   object
 20  cast_8        2295 non-null   object
 21  genre_0       2295 non-null   object
 22  genre_1       2295 non-null   object
 23  genre_2       2295 non-null   object
dtypes: int64(1), object(23)
memory usage: 430.4+ KB

In [53]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['director'] = le.fit_transform(data['director'])

In [55]:
data['type'] = le.fit_transform(data['type'])

In [59]:
data['cast_0'] = le.fit_transform(data['cast_0'])
data['cast_1'] = le.fit_transform(data['cast_1'])
data['cast_2'] = le.fit_transform(data['cast_2'])
data['cast_3'] = le.fit_transform(data['cast_3'])
data['cast_4'] = le.fit_transform(data['cast_4'])
data['cast_5'] = le.fit_transform(data['cast_5'])
data['cast_6'] = le.fit_transform(data['cast_6'])

In [61]:
data['cast_7'] = le.fit_transform(data['cast_7'])
data['cast_8'] = le.fit_transform(data['cast_8'])
data['genre_0'] = le.fit_transform(data['genre_0'])
data['genre_1'] = le.fit_transform(data['genre_1'])
data['genre_2'] = le.fit_transform(data['genre_2'])
data['rating'] = le.fit_transform(data['rating'])
data['country'] = le.fit_transform(data['country'])

In [64]:
data_new = data[['type','director','country','rating','cast_0','cast_1','cast_2','cast_3','cast_4','cast_5','cast_6','cast_7','cast_8','genre_0','genre_1','genre_2']]

In [81]:
data_rating1 = data_new[data_new['rating'] == 8]

In [82]:
data_rating1

,type,director,country,rating,cast_0,cast_1,cast_2,cast_3,cast_4,cast_5,cast_6,cast_7,cast_8,genre_0,genre_1,genre_2
0,0,580,291,8,854,1316,72,1265,1218,30,1246,937,0,12,12,8
18,0,671,170,8,502,211,354,1952,262,393,55,1508,968,0,4,4
26,0,1532,8,8,726,1020,620,1220,585,1738,88,0,0,12,13,28
30,0,1245,100,8,1087,1603,1678,714,337,1031,294,1070,180,7,9,8
35,1,861,170,8,1513,1774,1468,511,1764,1672,1250,241,730,8,14,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2269,0,437,281,8,1057,0,0,0,0,0,0,0,0,10,16,13
2275,0,393,281,8,253,758,842,994,500,1474,674,245,558,13,12,28
2278,0,1137,109,8,148,201,3,1176,1351,1555,1123,1096,782,12,12,8
2291,0,302,109,8,22,1198,896,1565,126,1341,815,381,688,7,9,8
2292,0,992,243,8,77,1525,1908,74,1081,34,0,0,0,12,13,28

In [65]:
data_new

,type,director,country,rating,cast_0,cast_1,cast_2,cast_3,cast_4,cast_5,cast_6,cast_7,cast_8,genre_0,genre_1,genre_2
0,0,580,291,8,854,1316,72,1265,1218,30,1246,937,0,12,12,8
1,0,1461,109,6,1263,44,1707,1236,0,0,0,0,0,7,13,14
2,0,1627,281,3,1393,1484,1463,1031,1216,270,642,1341,452,0,3,4
3,0,720,281,3,1393,1008,1228,854,759,338,120,851,134,12,11,28
4,0,750,281,3,376,246,1675,1036,806,886,1107,305,554,0,11,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2290,0,1114,63,6,1152,635,1769,32,44,612,69,77,676,12,12,8
2291,0,302,109,8,22,1198,896,1565,126,1341,815,381,688,7,9,8
2292,0,992,243,8,77,1525,1908,74,1081,34,0,0,0,12,13,28
2293,0,392,281,5,1012,721,1485,153,271,432,389,628,245,9,9,28
2294,0,1126,109,6,1657,1568,1384,1081,1147,962,111,261,0,12,13,13

# MODULE TRAINING

In [66]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [83]:
X = data_rating1[['type','director','country','rating','cast_0','cast_1','cast_2','cast_3','cast_4','cast_5','cast_6','cast_7','cast_8','genre_0','genre_1']]

In [84]:
Y = data_rating1['genre_2']

In [85]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.20)

In [90]:
clf = RandomForestClassifier(n_estimators = 100)  
  
# Training the model on the training dataset
# fit function is used to train the model using the training sets as parameters
clf.fit(X_train, y_train)
  
# performing predictions on the test dataset
y_pred = clf.predict(X_test)
  
# metrics are used to find accuracy or error
from sklearn import metrics  
print()
  
# using metrics module for accuracy calculation
print("ACCURACY OF THE MODEL: ", metrics.accuracy_score(y_test, y_pred))

ACCURACY OF THE MODEL:  0.6946107784431138

# decision tree

In [94]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn import tree

In [99]:
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [100]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.5868263473053892